sequenceDiagram
    participant Client
    participant Server

    Client->>Server: AUTH_REQ
    Server->>Client: AUTH_NONCE (unixTime, milTime, nonce)
    Client->>Server: AUTH_HMAC (id8, clientNonce, hmac32)
    Server->>Client: AUTH_ACK (hmac32) / AUTH_FAIL
    Client->>Client: AUTH_ACK verification 